[graph]
targets = [{ triple = "x86_64-unknown-linux-gnu" }]

[advisories]
version = 2
yanked = "deny"
ignore = []

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "0BSD",
    "Zlib",
    "AGPL-3.0",
    "AGPL-3.0-or-later",
    "Unicode-3.0",
]
confidence-threshold = 0.90

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/komrad-company/Khronika.git",
    "https://github.com/komrad-company/Kompiler.git",
    "https://github.com/komrad-company/Konnect.git",
]
